### ISSUE TITLE
[Feature Request] Accelerator checking via attributes

### ISSUE THREAD

**Issue by lunedis** [PrometheusSatyen/Cerebral#1]
Hey o/,

first of all, awesome application. It of enormous help when managing skill farms, especially with XML-API and Evemon being buggy (and soon phased out).

I was wondering if there are any plans to implement checking of accelerator status in the map (an icon when none is detected for example).

Using the /characters/#/implants and /characters/#/attributes one should be able to determine if an accelerator is running (+10 or +12 difference between actual and calculated attributes). Sadly there does not seem to be a way to determine booster run time with ESI, but a yes/no would be helpful.

Are you interested in pull requests?

Keep up the good work!

ingame: Mikokoel

**Comment by PrometheusSatyen** [comment]
Hi @lunedis,

The EVE ESI API does not return up to date attributes, if an accelerator expires at 14:00 and you refresh at 16:00, no change in attributes will be seen in the API. Once you log in to EVE, the attributes will then update on the API.

I intend to implement boosters/accelerators as soon as CCP adds an endpoint exposing them. Drop a thumbs up on this issue: https://github.com/ccpgames/esi-issues/issues/783 so that it gets ranked higher for CCP.

Going to close this off for now since I'm not going to implement a half-working implementation based on attributes.

**Re: Accepting pull requests:** not at this time.
